name: Release Charts

on:
  push:
    branches:
      - main
      - unstable

jobs:
  packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "devops@brightsec.com"
          git config --global user.name "Bright Security"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Helm Deps
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Release packages main
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
